
name: 优选IP

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 8 * * *'

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo  
      uses: actions/checkout@v3

    - name: Download IP list
      run: |
        rm -f addressesapi.txt
        curl https://cfno1.pages.dev/pure -o ip_list.txt
        sed -i '/^\s*$/d' ip_list.txt
        
    - name: Process IP list
      run: |
        while read line; do
        
          ip=$(echo $line | cut -d',' -f1)
        
          port=$(echo $line | cut -d',' -f2)
        
          desc=$(echo $line | cut -d',' -f3)
        
          if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] || [[ $ip =~ ^[a-fA-F0-9]{1,4}:[a-fA-F0-9:]{0,127}$ ]]; then
        
            address="$ip:$port"
        
            echo "$address#$desc" >> ip_list2.txt
        
          fi
        
        done < ip_list.txt
        
    - name: get my ip
      run: |
        curl https://box.zyjia.pp.ua/app/warp/ipull.php > ip_list3.txt
        sed -i '/^\s*$/d' ip_list3.txt
        

    - name: get cmliu ip
      run: |
        curl https://raw.githubusercontent.com/cmliu/WorkerVless2sub/main/addressesapi.txt > ip_list4.txt
        curl https://cfip.kaiche.tk/ > ip_list5.txt
        curl https://yxip.kaiche.tk/ > ip_list6.txt   
        #curl https://cf.idouyin.gq/ > ip_list7.txt           
        #curl https://addressesapi.090227.xyz/CloudFlareYes > ip_list8.txt                   
        curl https://dx.xxxxxxxx.tk/ > ip_list9.txt   
        curl https://dxv6.xxxxxxxx.tk/ > ip_list10.txt           
        cat ip_list2.txt >> addressesapi.txt
        cat ip_list3.txt >> addressesapi.txt
        cat ip_list4.txt >> addressesapi.txt 
        cat ip_list5.txt >> addressesapi.txt
        echo "" >> addressesapi.txt
        cat ip_list6.txt >> addressesapi.txt  
        echo "" >> addressesapi.txt
        cat ip_list9.txt >> addressesapi.txt
        echo "" >> addressesapi.txt
        cat ip_list10.txt >> addressesapi.txt     
        sed -i '/^\s*$/d' addressesapi.txt        
        rm -f ip_list.txt ip_list2.txt ip_list3.txt ip_list4.txt ip_list5.txt ip_list6.txt ip_list9.txt
        rm -f ip_list10.txt

    - name: Clean
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git checkout --orphan latest_branch
        git add -A
        git commit -am "自动获取优选IP"
        git branch -D main
        git branch -m main

    - name: Push
      run: git push -f origin main
