name: TG推送

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 加载当前的 GitHub 库
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Get Beijing Time
      id: time
      run: |
        TIME_ZONE="Asia/Shanghai"
        CURRENT_TIME=$(TZ=${TIME_ZONE} date +"%Y-%m-%d %H:%M:%S")
        echo "::set-output name=current_time::${CURRENT_TIME}"
      
    - name: 执行推送
      run: |
        head -n 6 addressesapi.txt > addressesapi_truncated.txt
        while IFS= read -r line; do
          ips+="$(echo "$line" | sed 's/#/, /g')"$'\n'
        done < addressesapi_truncated.txt
        message="今日优选 For: ${{ steps.time.outputs.current_time }}
        
        ${ips}......更多优选IP可通过自定义订阅方式获取
        ————
        vless快速体验订阅地址：https://sub.cmliucdn.tk/auto
        vless自定义订阅详细使用方法：
        https://sub.cmliucdn.tk/sub?host=[你的Vless域名]%26uuid=[你的UUID]%26path=[你的ws路径]
        
        快速订阅方式,如果你的vless是通过worker部署可填入以下参数后获取节点订阅信息
        https://sub.cmliucdn.tk/sub?host=[你的Worker域名]%26uuid=[你的UUID]
        实际使用时请去掉[ ]符号，Worker部署优先使用自定义域！！！
        ————
        vmess快速体验订阅地址：https://vmess.cmliucdn.tk/auto
        vmess自定义订阅详细使用方法：
        https://vmess.cmliucdn.tk/sub?cc=[Vmess服务名字]%26host=[你的Vmess域名]%26uuid=[你的UUID]%26path=[你的ws路径]%26alterid=[额外ID]%26security=[加密方式]
        
        *cc 非必填项，可能会影响使用在线订阅转换,推荐使用地区代号，例如HK、SG、US
        *alterid 非必填项，默认0
        *security 非必填项，默认auto
        
        快速订阅方式
        https://vmess.cmliucdn.tk/sub?host=[你的Vmess域名]%26uuid=[你的UUID]%26path=[你的ws路径]
        
        实际使用时请去掉[ ]符号，注意worker不支持vmess！worker不支持vmess！worker不支持vmess！！！
        ————
        注意：您可以将此链接分享传播到任何地方😁
        顺便给3Kmfi6HP大佬、白嫖哥、Mingyu大佬敬个礼"
        
        # wget -qO- "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TG_TESTPD_ID }}&text=$message"
        curl -X POST -H "Content-Type: application/x-www-form-urlencoded" \
        -d "chat_id=${{ secrets.TG_PD_ID }}" \
        -d "text=${message}" \
        "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage"
        
